# Generated by Django 3.2.4 on 2021-06-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=10)),
            ],
        ),
    ]
